### ISSUE TITLE
Support pod structure?

### ISSUE THREAD

**Issue by cowboy** [johnotander/ember-cli-gravatar#14]
When I attempt to use this, I get an error:

```bash
$ ember g ember-cli-gravatar --verbose
version: 0.1.7
Could not find watchman, falling back to NodeWatcher for file system events
installing
You specified the pod flag, but this blueprint does not support pod structure. It will be generated with the default structure.
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  cached git://github.com/blueimp/JavaScript-MD5.git#1.1.0
Installed browser packages via Bower.
```

Can you help?

**Comment by johnotander** [comment]
Hrm, weird. I'll get digging.

Is this error raised when installing the addon with the new syntax?: `ember install:addon ember-cli-gravatar`?

**Comment by johnotander** [comment]
Also, I recommend upgrading the latest version of the ember-cli `0.1.11`.

**Comment by johnotander** [comment]
Okay, so I was able to reproduce the error message myself, with an `ember-cli@0.1.11` test app, as well:

```
test-app|||master* $ ember install:addon ember-cli-gravatar    
version: 0.1.11
Could not find watchman, falling back to NodeWatcher for file system events
Installed packages for tooling via npm.
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  cached git://github.com/blueimp/JavaScript-MD5.git#1.1.0
Installed browser packages via Bower.
Installed addon package.
```

Though, despite the error, the gravatar component still seems to work. Not sure what's going on with that, but I will continue digging.

@cowboy, could you please try to reinstall `ember-cli-gravatar`, and let me know whether it is working in your app even with the installation error message? Thanks.

**Comment by cowboy** [comment]
I'm under a time crunch, so I just stripped out the component and used this instead. https://gist.github.com/ryrych/6145566

If I have time after I'm all done to test, I will!

**Comment by johnotander** [comment]
Sounds great, thanks!

**Comment by trabus** [comment]
Sorry about this, it was [happening with any blueprint that didn't have files in it](https://github.com/ember-cli/ember-cli/issues/3142). 
The good news is, it was a benign warning, and didn't affect the install process. And the even better news is that it's gone as of ember-cli 0.1.13. 

Please feel free to close this issue.

**Comment by johnotander** [comment]
Ah, yes. I forgot to close this after the issue was sorted out on the ember-cli end of things.

Thanks so much for your hard work @trabus and the rest of the ember-cli team. <3.
