### ISSUE TITLE
Providing alt attribute updates email

### ISSUE THREAD

**Issue by jonnedeprez** [johnotander/ember-cli-gravatar#15]
By defining alt as `alt: Ember.computed.alias('email')` the alt property can not be set without also updating the email field. I noticed this issue when suddenly the email and name properties of my models appeared to be bound to eachother...

**Comment by johnotander** [comment]
Ah, yeah. I've been meaning to change this. I'll be removing the alias shortly and pushing a new version.

**Comment by johnotander** [comment]
Published to npm: `ember-cli-gravatar@2.3.0`.
