### ISSUE TITLE
Rename `default` to `defaultImage`

### ISSUE THREAD

**Issue by dhilipsiva** [johnotander/ember-cli-gravatar#20]
`default` is a Javascript Reserved keyword. While this is handled smartly by most browsers, others complain a Parse Error. 
![screen shot 2015-04-14 at 13 45 15](https://cloud.githubusercontent.com/assets/502170/7133054/d11d402e-e2ac-11e4-9982-8b51059784ab.png)

**Comment by dhilipsiva** [comment]
Can we start working on version `3.0` and push it? These are critical.

**Comment by johnotander** [comment]
Sure thing :smiley_cat:

**Comment by johnotander** [comment]
Published to npm as `ember-cli-gravatar@2.5.2`. I published this as `2.5.2` as it isn't a breaking change. However, for `3.0` I'm wondering if we should rename this property to `defaultImage` to avoid the keyword altogether.

Closes #21

**Comment by dhilipsiva** [comment]
Yeah, that is why I actually created: https://github.com/johnotander/ember-cli-gravatar/issues/20#issuecomment-92691176 . We should rename it to `defaultImage`, that sounds better and unambiguous.

**Comment by johnotander** [comment]
Great, got all the related issues into the [`3.0`](https://github.com/johnotander/ember-cli-gravatar/milestones/3.0) milestone.

**Comment by johnotander** [comment]
3.0.0 is released. Thanks for all your help @dhilipsiva!

**Comment by dhilipsiva** [comment]
Whoa, Great! That was quick. No, thank you for the addon @johnotander :smile:
