### ISSUE TITLE
Support hash directly in addition to email

### ISSUE THREAD

**Issue by swalkinshaw** [johnotander/ember-cli-gravatar#35]
Hey @johnotander, any interested in supporting an option of `hash` which, if present, would be used in place of `md5(email)`?

If so I'd be willing to do a PR. We'd rather use this component instead of duplicating the work (and great tests!) but we aren't exposing emails publicly so instead our API has the hash already.

**Comment by johnotander** [comment]
Of course! That'd be great.

**Comment by johnotander** [comment]
This functionality has been added in version `3.4.0`.
